# Lecture 9 - More on Loops

## Overview, Objectives, and Key Terms
 
In [Lecture 8](ME400_Lecture_8.ipynb), the use of `while` loops in Python introduced to solve problems requiring iteration.  The `while` loop structure in Python is very similar to structure introduced via pseudocode in
[Lecture_5](ME400_Lecture_5.ipynb).  In this lecture, an additional `for`-loop construct is introduced, which reduces the amount of "bookkeeping" required in some cases.  All loops can also be *nested*, which provides substantial flexibility when processing data, defining multidimensional arrays, and performing similar, potentially multidimensional tasks.



### Objectives

By the end of this lesson, you should be able to

- Use a `for` loop to solve simple problems using iteration
- Use nested `for` loops to fill the elements of a multidimensional array.
- Use the graphical debugger in Spyder to trace and debug a program with iteration



### Key Terms

- `for`
- `range`
- `continue`
- loop variable
- dependent loop variable

In [1]:
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = "all"

## The `for` Loop

Remember our `while` solution for printing out each element of an array `a`:

```python
# print out the elements of an array using a while loop
import numpy as np
a = np.array([1, 1, 2, 3, 5, 8, 13])
n = len(a)
i = 0
while i < n:    # always remember the :
    print(a[i]) # indented 4 spaces
    i = i + 1   # also indented 4 spaces
```

The same thing can be accomplished with a `for` loop:


In [2]:
# print out the elements of an array using a for loop
import numpy as np
a = np.array([1, 1, 2, 3, 5, 8, 13])
n = len(a)
for i in range(0, n): # always remember the :
    print(a[i]) # indented 4 spaces

1
1
2
3
5
8
13


Some differences:
- `while` requires initialization of the counter variable `i`, but `for` does not.
- `while i < n` becomes `for i in range(0, n)`
- `while` is based on a condition involving `i`, but `for` is based on a fixed number of values for `i`

### `range`

Similar to `np.arange`, but restricted to integers:
```python
range(start, stop, stride)
```
where `start` is the first value, `stop` is the exclusive upper bound, and `stride` is the step between values (default is 1).

**Examples..**

### Beyond `range`

The `for i in sequence` construct in Python is not limited to `range`.  In fact, `sequence` can be any sequential type (e.g., `ndarray`, `str`, and, we'll see, `list` and `tuple`).  Then `i` becomes elements of that sequence.

In [3]:
for i in np.linspace(0, 1, 5):
    print(i)

0.0
0.25
0.5
0.75
1.0


In [4]:
for j in np.array([[1,2,3],[2,3,4],[5,6,7]]):
    print(j)

[1 2 3]
[2 3 4]
[5 6 7]


In [5]:
for c in "hello":
    print(c)

h
e
l
l
o


## A Pythonic Quirk

Python's `while` and `for` loops are not quite the same "under the hood."

In [6]:
n = 5
i = 0
while i < n:
    print("i = ", i)
    i += 2

i =  0
i =  2
i =  4


In [7]:
# A "quirky" for loop
for j in range(n):
    print ("j = ", j)
    j += 2

j =  0
j =  1
j =  2
j =  3
j =  4


## Nested `for` loops

Just like `if` statements can be nested, so, too, can `for` (and `while`) loops be nested.  While nested `if` statements can always be written as (potentially much) more complicated, single statements, there are some tasks for which nested loops are truly required---but I have not proven that!



**Exercise**: Use a nested `for` loop to find the sum of the elements of $5\times 5$ array of random numbers.

The cumulative sum of an array is another array of the same length whose $i$th element is defined as

$$
  c_i = \sum^i_{j=0} a_j \, .
$$

For example, the cumulative sum of an array of three ones has the elements 1, 2, and 3.

**Exercise**: Use a `for` loop to compute the cumulative sum of an array of 5 random numbers.

**Exercise**: Starting with `A = np.zeros((5, 5))`, use two loops to produce
```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

## Recap

By now, you should be able to

- Use a `for` loop to solve simple problems using iteration
- Use nested `for` loops to fill the elements of a multidimensional array.
- Use the graphical debugger in Spyder to trace and debug a program with iteration

Reminder: **Exam 1** is next week Friday.  