# Lecture 3 - Basic Data Processing with NumPy and Matplotlib

## Overview, Objectives, and Key Terms
 
In this lesson, we'll explore some core features of NumPy and Matplotlib and extend our Python based "calculator" to include processing of *arrays* of data.  [NumPy](http://www.numpy.org/) is the basic numerical package for Python.  A lot of its utility comes from its numerical, multidimensional array type, :code:`ndarray`. Use of these arrays in a *vectorized* way often leads to significantly faster (and much more compact) code.  Moreover, the array-valued results of numerical computations are  easily visualized using Matplotlib, which was originally developed to provide MATLAB-like graphics in the Python environment.   

I think it's so important that students can create, process, and display data that I highlight it early in the course and revisit it throughtout.  NumPy and Matplotlib together provide about the easiest way to work with data.

### Objectives

By the end of this lesson, you should be able to

- *define and manipulate one-dimensional and two-dimensionanal NumPy arrays*
- *load and save data from and to text files*
- *produce plots of data following best practices*


### Key Terms

- `numpy`
- `ndarray` 
- `np.array`
- `np.ones`
- `np.zeros`
- `np.linspace`
- `np.sin`
- `matplotlib.pyplot`

## NumPy and One-Dimensional Arrays

NumPy is not part of Python, but it is a well-supported package.  It comes by default in the Anaconda distribution, so you should already have it. Like all packages, we can import NumPy via 

In [1]:
import numpy

However, it is far more common to use 

In [3]:
import numpy as np

The difference between these approaches is in how we use the `numpy` module.  Built in to `numpy` are a number of same functions we saw in `math`, e.g., `sin`.  Hence, we could use `numpy.sin(1.0)`, but if we import `numpy` as `np`, we would use `np.sin(1.0)`.  I recommend the latter because (1) it is shorter and (2) most online documentation uses the `np` abbreviation.

> **Note**: Use `import numpy as np` instead of `import numpy`.

### A Motivating Example

Here's a common task easily solved using NumPy: evaluate a
mathematical function `f(x)` at discrete
points.  Why discrete data? Perhaps because that's all the input data 
we have, e.g., from measurements,  or perhaps we're trying to plot that 
function.  In any case, this is where NumPy excels.  Consider the specific
case for which we want to evaluate $f(x) = \sin(x)$
for $x \in [0, 1]$, where `x` is to limited to 10 evenly-spaced
points.  

Here's what we need to do.  First, always make sure NumPy is imported; in this 
notebook, we did that above, but here it is again for completeness.

In [4]:
import numpy as np 

Now, we create an array `x` with 10, evenly-spaced points from 0 to 1
using the function `np.linspace` as follows:

In [6]:
x = np.linspace(0, 1, 10)
x

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

Finally, we evaluate the function `np.sin` at these points.

In [7]:
y = np.sin(x)
y

array([ 0.        ,  0.11088263,  0.22039774,  0.3271947 ,  0.42995636,
        0.52741539,  0.6183698 ,  0.70169788,  0.77637192,  0.84147098])

Note that :code:`np.sin(x)` is used and not `math.sin(x)`.  
That's because :code:`x` in this case is a `ndarray`, to which the
base Python :code:`math` functions do not apply.  

The function `np.linspace(a, b, n)` gives `n` evenly-spaced points starting 
with `a` and ending with `b`.  Writing the equivalent C++ or
Fortran to define such an `x` is a royal pain; that's why Python + 
NumPy (or MATLAB/Octave) is so nice for this type of problem.

### Creating and Manipulating 1-D Arrays

We already saw one way to create a one-dimensional array, i.e., `np.linspace`.  There are many other ways to create these arrays.  Suppose we have a list of numbers, e.g., 1.5, 2.7, and 3.1, and we'd like to make an array filled with these numbers.  That's easy:

In [10]:
a = np.array([1.5, 2.7, 3.1])
a

array([ 1.5,  2.7,  3.1])

(It turns out that `[1.5, 2.7, 3.1]` is actually a Python `list`, but we'll cover those later on when we need them; for now, we'll stick with NumPy arrays exclusively.)

The common ways to make 1-D arrays are listed in the table below.

| function      | example use                     | what it creates creates     | 
|---------------|---------------------------------|-----------------------------|
| `np.array`    | `np.array([1.5, 2.7, 3.1])`     | `array([ 1.5,  2.7,  3.1])` |
| `np.linspace` | `np.linspace(0, 1, 3)`          | `array([ 0. ,  0.5,  1. ])` |
| `np.ones`     | `np.ones(3)`                    | `array([ 1.,  1.,  1.])`    |
| `np.zeros`    | `np.zeros(3)`                   | `array([ 0.,  0.,  0.])`    |
| `np.arange`   | `np.arange(1, 4)`               | ` array([1, 2, 3])`         |



In [9]:
np.ones(2)

array([ 1.,  1.])

In [ ]:

Another useful aspect of NumPy arrays is that the basic arithmetic 
operations of Python apply to such array a *element-wise* operations.
For example, consider the following code: